Add sample code for expense parser (folder expense-parser-python)
GoogleCloudPlatform/document-ai-samples pull request #16
Opened 2022-03-18 20:47 UTC by jiya-zhang

2022-03-30 17:04 UTC, galz10 commented on community/expense-parser-python/cloud-functions/main.py
> +import re
I don't think you use this

2022-03-30 17:04 UTC, galz10 commented on community/expense-parser-python/cloud-functions/main.py
> +from datetime import datetime
I don't think you use this

2022-03-30 17:06 UTC, galz10 commented on community/expense-parser-python/table-schema/bq_schema.json
> +  ]
add new line

2022-03-30 18:23 UTC, galz10 requested changes
After fixing the few comments could you run pylint and fix all the lint errors

2022-03-31 19:50 UTC, jiya-zhang commented on community/expense-parser-python/README.md
> +1. Create a Google Cloud Platform Project
Can I just specify that they should use Cloud Shell?

2022-04-01 18:48 UTC, kweinmeister commented
Hi @jiya-zhang - good news, we've automatically resolved several of the linting issues with the OwlBot post-processor.

Please also ensure that your files include a copyright header at the top.. You can look at other examples in the repo.

Thanks!

2022-04-05 18:01 UTC, galz10 commented on community/expense-parser-python/README.md
> +1. Create a Google Cloud Platform Project
I think using the cloud cli is better then Cloud shell for this but yes you can

2022-04-15 20:53 UTC, kweinmeister approved these changes

2022-04-15 20:54 UTC, merged