Metadata mapping functionality
GoogleCloudPlatform/document-ai-samples pull request #217
Opened 2022-12-09 14:10 UTC by mservidio

Metadata mapping functionality

2022-12-20 23:02 UTC, holtskinner requested changes

2022-12-21 17:51 UTC, mservidio commented on bq-connector/docai_bq_connector/doc_ai_processing/Processor.py
>          # operation.metadata.individual_process_statuses[0].human_review_status
This isn't fully implemented yet. I'll remove the commented code for now.

2022-12-21 18:16 UTC, mservidio commented on bq-connector/docai_bq_connector/connector/DocAIBQConnector.py
> +        self.metadata_mapper = BqMetadataMapper(metadata_mapping_info if metadata_mapping_info else {})
The problem is that even with the default value set to {}, a None may still be passed through. I would prefer not to instantiate the BqMetadataMapper object at all if no metadata is provided. Will clean this up in a future update.

2022-12-22 16:22 UTC, holtskinner approved these changes

2022-12-22 16:23 UTC, merged