feat: Incubator Tools - 7th Iteration
GoogleCloudPlatform/document-ai-samples pull request #804
Opened 2024-05-08 07:23 UTC by dmoonat

Adding Document AI tools developed by Incubator team

2024-05-15 18:41 UTC, holtskinner commented
Lint errors need to be fixed. Several spelling errors in as well, in file names and in notebooks

2024-05-15 18:49 UTC, holtskinner requested changes
See comments

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/Combine_two_processors_output/README.md
README not needed for Jupyter Notebooks

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/Combine_two_processors_output/combine_two_processor_output_tool.ipynb
Make folder name consistent with notebook name or remove folder.

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/DocAI_Json_to_Canonical_Json_Conversion/Docai_json_to_canonical_json_conversion.ipynb
Can you add more specific description or name of what "Canonical JSON" is? Also, don't use the term "proto" most developers outside of google don't know what this is.

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/DocAI_Json_to_Canonical_Json_Conversion/README.md
README not needed for notebook

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/date_entity_normalization/README.md
Same comment as above with README and notebook

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/enrich_address_for_invoice/enrich_address_for_invoice.ipynb
Lots of duplicate code from other notebooks. (Downloading from GCS) Any way to combine/simplify?

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/normalize_date_value_19xx_to_20xx/normalize_date_value_19xx_to_20xx.ipynb
How can we consistently determine when the date is interpreted incorrectly and this needs to be used?

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/reverse_annotation_tool/reverse_annotation_tool.ipynb
Isn't there already a reverse annotation tool in this repo?

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/schema_comparision/contract_schema.json
Were these supposed to be removed?

2024-05-15 18:49 UTC, holtskinner commented on incubator-tools/special_character_removal/special_character_removal.ipynb
What is the use case for this? What kind of special characters are removed and why?

Can a description be added for how this is to be used?

2024-05-16 11:32 UTC, vijay-google commented on incubator-tools/Combine_two_processors_output/README.md
yeah, will remove README file

2024-05-16 11:33 UTC, vijay-google commented on incubator-tools/Combine_two_processors_output/combine_two_processor_output_tool.ipynb
Sure, will maintain consistency for folder-name and notebook-name.

2024-05-16 11:33 UTC, vijay-google commented on incubator-tools/DocAI_Json_to_Canonical_Json_Conversion/README.md
yeah, will remove README file

2024-05-16 11:35 UTC, vijay-google commented on incubator-tools/date_entity_normalization/README.md
yeah, will remove README file. For future PR's we will not add README's.

2024-05-16 12:04 UTC, vijay-google commented on incubator-tools/reverse_annotation_tool/reverse_annotation_tool.ipynb
No @holtskinner, it is not available. Cross verified with incubator-tools folder didn't found it.

2024-05-16 12:29 UTC, venkatasantosh23 commented on incubator-tools/enrich_address_for_invoice/enrich_address_for_invoice.ipynb
we removed duplicated code

2024-05-16 12:55 UTC, venkatasantosh23 commented on incubator-tools/special_character_removal/special_character_removal.ipynb
This process removes special characters like hyphens (-) and forward slashes (/) from the amount field. This is done because the presence of these characters can interfere with the ability of parsing elements to correctly identify the amount values. 

Updated same in the documentation

2024-05-16 13:18 UTC, venkatasantosh23 commented on incubator-tools/DocAI_Json_to_Canonical_Json_Conversion/Docai_json_to_canonical_json_conversion.ipynb
we have updated the term "proto" to document AI object and also added a description for "Canonical Json" also with it's Json structure

2024-05-16 13:21 UTC, ssnvenkatesh888 commented on incubator-tools/schema_comparision/contract_schema.json
Yes, they were supposed to be removed

2024-05-17 15:42 UTC, holtskinner approved these changes

2024-05-17 15:42 UTC, merged